FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY ./Client ./Client
COPY ./Server ./Server
COPY *.sln ./

RUN dotnet publish ./Client/Client.csproj -c Release -o /app/Server/wwwroot

RUN dotnet publish ./Server/Server.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /out ./

ENTRYPOINT ["dotnet", "Server.dll"]
